spring:
  application:
    name: freshPotato
  datasource:
    url: jdbc:mariadb://localhost:3306/your_database_name
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true