spring:
  application:
    name: MovieMiner
  mongodb:
    uri: mongodb://localhost/dump


miner:
  dump:
    path: "/mnt/ssd/wikidata-dump.json.bz2"

threadpool:
  size:
    initial: 5
    max: 1000

reader:
  buffer:
    MB: 700